-- Generated by scripts/fix-pins.js — do not edit by hand.
-- Regenerates pin_salt / pin_hash for the listed demo accounts.

UPDATE users SET pin_salt = '89a03aa4d0beab9e9538d7eb7c5dac53', pin_hash = '5d2cffc861b3fbe895c453e61888653b5b8205259130a3671e8edb7a5dc0cc8c' WHERE student_no = '2021-00234'; -- PIN: 1234
UPDATE users SET pin_salt = '0cd8718ac447647d5cba8757e4f83a44', pin_hash = 'c6fc8eeca71146c777d0af7af52b677adc6c11be98ed0d42251aca288081f2a3' WHERE student_no = '2020-01187'; -- PIN: 1234
UPDATE users SET pin_salt = 'a59496ac710c721bad211f986ce8ecdd', pin_hash = 'a09c549652fc7b0e3e09a171ac54d5a3f03fe0f6913d2235d32fd87881d9bab7' WHERE student_no = '2022-00456'; -- PIN: 1234
UPDATE users SET pin_salt = '5e7a974e3bd52910c083afd5f63686b7', pin_hash = '424d0d7a102167f07f8d9941df976ab3a2634d9698ac397ea8209949d446b33c' WHERE student_no = '2019-00789'; -- PIN: 1234
UPDATE users SET pin_salt = '3c8bcf8222505a04a951b59f6b373ef6', pin_hash = '0c586031540d6bd1ecbd5cdaf1dba7bb3115f1e9e4e575d8c7ab8c7da6eb31df' WHERE student_no = '2021-00912'; -- PIN: 1234
UPDATE users SET pin_salt = 'ee2743beffe0a65911c4d1c9268cfce7', pin_hash = '7e697f221fc336bad17851c747492b7445848b9937547b17abdb337540d6406c' WHERE student_no = 'STF-00045'; -- PIN: 6789
UPDATE users SET pin_salt = '1f8510dfd4d29a7ce131469ba4e15741', pin_hash = 'c36e11bde59ab33a974048b2bcbafdeda897cd52585f828d8898a63d3de4364c' WHERE student_no = 'STF-00089'; -- PIN: 7890
UPDATE users SET pin_salt = '4b5bee04825633708b771a3524a764cb', pin_hash = 'eb30c1b96b40feac072875493a4ee5876b4a7701892c9aa0b1ce3b248aea73ff' WHERE student_no = 'ADM-00012'; -- PIN: 8901

-- Done.
