// scripts/fix-pins.js
// CSPC WhereITis — Lost & Found Management System
// -----------------------------------------------------------------------
// Regenerates pin_salt/pin_hash pairs for a list of seeded demo accounts
// and prints UPDATE statements to stdout.
//
// Usage:
//   node scripts/fix-pins.js > fix-pins.sql
//   mysql -u root whereitis < fix-pins.sql
//
// MIDTERM COMPROMISE — see models/userModel.js for the full rationale.
// This regenerates SHA-256(salt || pin), the same scheme already used
// everywhere else in the app; it does not introduce bcrypt or change the
// mechanism. Edit the PAIRS array below with the student numbers and
// PINs you want, then re-run.
// -----------------------------------------------------------------------

const crypto = require('crypto');

// Edit this array with the student_no / pin pairs to fix.
const PAIRS = [
  { student_no: '2021-00234', pin: '1234' },
  { student_no: '2020-01187', pin: '1234' },
  { student_no: '2022-00456', pin: '1234' },
  { student_no: '2019-00789', pin: '1234' },
  { student_no: '2021-00912', pin: '1234' },
  { student_no: 'STF-00045',  pin: '6789' },
  { student_no: 'STF-00089',  pin: '7890' },
  { student_no: 'ADM-00012',  pin: '8901' },
];
function escapeSqlString(value) {
  // Minimal escaping for the fixed, known-safe values this script emits
  // (student numbers are hardcoded above, not user input from a form) —
  // still escapes single quotes and backslashes defensively.
  return String(value).replace(/\\/g, '\\\\').replace(/'/g, "\\'");
}

console.log('-- Generated by scripts/fix-pins.js — do not edit by hand.');
console.log('-- Regenerates pin_salt / pin_hash for the listed demo accounts.');
console.log('');

PAIRS.forEach(({ student_no, pin }) => {
  if (!/^\d{4}$/.test(pin)) {
    console.error(`Skipping ${student_no}: PIN "${pin}" is not exactly 4 digits.`);
    return;
  }

  const salt = crypto.randomBytes(16).toString('hex'); // 32 hex chars
  const hash = crypto.createHash('sha256').update(salt + pin).digest('hex'); // 64 hex chars

  console.log(
    `UPDATE users SET pin_salt = '${salt}', pin_hash = '${hash}' ` +
    `WHERE student_no = '${escapeSqlString(student_no)}'; -- PIN: ${pin}`
  );
});

console.log('');
console.log('-- Done.');